[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "Py3D"
description = "A 3D graphics library in Python"
version = "0.1.0"
authors = [
  { name = "Jemtaly" },
]
license = { file = "LICENSE" }
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
  "numpy>=1.21",
]

[project.optional-dependencies]
qt = [
  "PyQt5>=5.15",
]

[project.scripts]
plot3d = "py3d.frontends.tkinter.plot3d:main"
objviewer = "py3d.frontends.tkinter.objviewer:main"
plot3d-qt = "py3d.frontends.qt.plot3d:main [qt]"
objviewer-qt = "py3d.frontends.qt.objviewer:main [qt]"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
